server:
  port: 8082
  
spring:  datasource:    url:  jdbc:mysql://localhost:3306/AdminDB
    password: Deepak13*
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:    hibernate:      ddl-auto: update
    show-sql: true    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      application:    name: ADMIN-SERVICE
    
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
  file:
    name: flight-user-ws.log