server:
  port: 8081
  
spring:  datasource:    url:  jdbc:mysql://localhost:3306/UserDB
    password: Deepak13*
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:    hibernate:      ddl-auto: update
    show-sql: true    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      application:    name: USER-SERVICE
    
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
  file:
    name: flight-user-ws.log
    
# App Properties
flightapp:
  user:
    jwtCookieName: flightApp
    jwtExpirationMs: 86400000
    jwtSecret: flightAppSecretKey